"""
Power Band Binary Reader

This script reads binary files (.dat) generated by AudioProcLowLevel.generate_output()
and converts them back to relative power values in dB.

The binary files contain uint8 values representing relative powers in dB.
- Mono files: 1D array of N_bands bytes
- Stereo files: 2D array flattened to 1D of 2*N_bands bytes
"""

import os
import sys
import numpy as np
import pandas as pd


FILE_PATH = 'C:/repo/boya/data/20251106_224946_mock.dat'

# Add parent directory to path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def load_third_octave_bands():
    """
    Load third-octave bands configuration from CSV.
    
    Returns:
        pandas.DataFrame: DataFrame with third-octave bands information.
    """
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    csv_path = os.path.join(base_dir, "support", "third_octave_bands.csv")
    
    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"Third-octave bands file not found: {csv_path}")
    
    bands_df = pd.read_csv(csv_path)
    
    # Filter bands in the range from 1 Hz to 100000 Hz (same as in BL_calculator)
    f_min = 1.0
    f_max = 100000.0
    bands_df = bands_df[(bands_df['fl'] >= f_min) & (bands_df['fh'] <= f_max)].copy()
    
    return bands_df


def read_binary_file(file_path, n_channels=None):
    """
    Read binary file (.dat) containing relative power values.
    
    Args:
        file_path (str): Path to the .dat binary file.
        n_channels (int, optional): Number of channels (1 for mono, 2 for stereo).
                                   If None, will try to auto-detect based on file size
                                   and expected number of bands.
    
    Returns:
        tuple: (powers_array, n_channels, n_bands)
               - powers_array: numpy.ndarray with relative powers in dB
                 - If mono: 1D array of shape (n_bands,)
                 - If stereo: 2D array of shape (n_bands, 2)
               - n_channels: Number of channels detected or specified
               - n_bands: Number of third-octave bands
    """
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Binary file not found: {file_path}")
    
    # Read binary file as uint8
    data_uint8 = np.fromfile(file_path, dtype=np.uint8)
    n_bytes = len(data_uint8)
    
    # Load third-octave bands to determine expected number of bands
    bands_df = load_third_octave_bands()
    n_bands_expected = len(bands_df)
    
    # Auto-detect number of channels if not specified
    if n_channels is None:
        if n_bytes == n_bands_expected:
            n_channels = 1  # Mono
        elif n_bytes == 2 * n_bands_expected:
            n_channels = 2  # Stereo
        else:
            # Try to determine if it's divisible by expected bands
            if n_bytes % n_bands_expected == 0:
                n_channels = n_bytes // n_bands_expected
                print(f"Warning: File size ({n_bytes} bytes) is {n_channels} times "
                      f"the expected number of bands ({n_bands_expected}). "
                      f"Assuming {n_channels} channels.")
            else:
                raise ValueError(
                    f"Cannot determine number of channels. "
                    f"File size ({n_bytes} bytes) does not match expected "
                    f"band count ({n_bands_expected} for mono, "
                    f"{2 * n_bands_expected} for stereo). "
                    f"Please specify n_channels manually."
                )
    
    # Reshape data based on number of channels
    if n_channels == 1:
        # Mono: 1D array
        powers = data_uint8.astype(np.float64)
        n_bands = len(powers)
    elif n_channels == 2:
        # Stereo: reshape to 2D array
        if n_bytes != 2 * n_bands_expected:
            # Use actual size to determine number of bands
            n_bands = n_bytes // 2
            if n_bytes % 2 != 0:
                raise ValueError(f"File size ({n_bytes} bytes) is not divisible by 2 for stereo.")
        else:
            n_bands = n_bands_expected
        
        powers = data_uint8.reshape(n_bands, 2).astype(np.float64)
    else:
        raise ValueError(f"Unsupported number of channels: {n_channels}")
    
    print(f"Read {n_bytes} bytes from {file_path}")
    print(f"Detected: {n_channels} channel(s), {n_bands} bands")
    
    return powers, n_channels, n_bands


def save_to_csv(powers, output_path, n_channels):
    """
    Save power values to CSV file.
    
    Args:
        powers (numpy.ndarray): Power values array.
        output_path (str): Path to output CSV file.
        n_channels (int): Number of channels (1 or 2).
    """
    if n_channels == 1:
        df = pd.DataFrame({'rel_power_dB': powers})
    else:
        df = pd.DataFrame({
            'rel_power_dB_ch1': powers[:, 0],
            'rel_power_dB_ch2': powers[:, 1]
        })
    
    df.to_csv(output_path, index=False)
    print(f"Saved to CSV: {output_path}")


def print_summary(powers, n_channels, bands_df):
    """
    Print summary of power values.
    
    Args:
        powers (numpy.ndarray): Power values array.
        n_channels (int): Number of channels.
        bands_df (pandas.DataFrame): Third-octave bands DataFrame.
    """
    n_bands = len(powers) if powers.ndim == 1 else powers.shape[0]
    
    print("\n" + "="*60)
    print("Power Band Summary")
    print("="*60)
    print(f"Number of bands: {n_bands}")
    print(f"Number of channels: {n_channels}")
    
    if n_channels == 1:
        print(f"Min power: {np.min(powers):.2f} dB")
        print(f"Max power: {np.max(powers):.2f} dB")
        print(f"Mean power: {np.mean(powers):.2f} dB")
    else:
        print(f"Channel 1 - Min: {np.min(powers[:, 0]):.2f} dB, "
              f"Max: {np.max(powers[:, 0]):.2f} dB, "
              f"Mean: {np.mean(powers[:, 0]):.2f} dB")
        print(f"Channel 2 - Min: {np.min(powers[:, 1]):.2f} dB, "
              f"Max: {np.max(powers[:, 1]):.2f} dB, "
              f"Mean: {np.mean(powers[:, 1]):.2f} dB")
    
    print("="*60)


def print_table(powers, n_channels, bands_df):
    """
    Print all power values in a table format.
    
    Args:
        powers (numpy.ndarray): Power values array.
        n_channels (int): Number of channels.
        bands_df (pandas.DataFrame): Third-octave bands DataFrame.
    """
    n_bands = len(powers) if powers.ndim == 1 else powers.shape[0]
    
    # Filter bands to match the number of power values
    # Apply same filtering as in BL_calculator (Nyquist filter would depend on sample rate)
    # For now, we'll use the filtered bands_df and match by length
    bands_filtered = bands_df.copy()
    if len(bands_filtered) > n_bands:
        # If we have more bands than power values, take the first n_bands
        bands_filtered = bands_filtered.iloc[:n_bands].copy()
    elif len(bands_filtered) < n_bands:
        # If we have fewer bands, pad with NaN (shouldn't happen normally)
        print(f"Warning: Number of bands ({len(bands_filtered)}) doesn't match "
              f"power values ({n_bands})")
    
    # Create DataFrame with band information and power values
    if n_channels == 1:
        # Mono: one column for power
        table_df = pd.DataFrame({
            'Band': range(1, n_bands + 1),
            'fc (Hz)': bands_filtered['fc'].values[:n_bands],
            'fl (Hz)': bands_filtered['fl'].values[:n_bands],
            'fh (Hz)': bands_filtered['fh'].values[:n_bands],
            'rel_power_dB': powers
        })
    else:
        # Stereo: two columns for power
        table_df = pd.DataFrame({
            'Band': range(1, n_bands + 1),
            'fc (Hz)': bands_filtered['fc'].values[:n_bands],
            'fl (Hz)': bands_filtered['fl'].values[:n_bands],
            'fh (Hz)': bands_filtered['fh'].values[:n_bands],
            'rel_power_dB_ch1': powers[:, 0],
            'rel_power_dB_ch2': powers[:, 1]
        })
    
    # Format float columns for better display
    pd.set_option('display.float_format', lambda x: f'{x:.2f}' if abs(x) < 1000 else f'{x:.2e}')
    pd.set_option('display.max_rows', None)
    pd.set_option('display.max_columns', None)
    pd.set_option('display.width', None)
    pd.set_option('display.max_colwidth', None)
    
    print("\n" + "="*80)
    print("Power Band Values Table")
    print("="*80)
    print(table_df.to_string(index=False))
    print("="*80)


def main():
   
    """Main function."""
       
    try:
        # Read binary file
        powers, n_channels, n_bands = read_binary_file(FILE_PATH)
        
        # Load bands information
        bands_df = load_third_octave_bands()
        
        # Print summary
        print_summary(powers, n_channels, bands_df)
        
        print_table(powers, n_channels, bands_df)
        
        return powers, n_channels, n_bands
        
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()

